# Substrata
[colors]
foreground = "#b5b4c9" 
background = "#191c25"
cursor_bg = "#b5b4c9" 
cursor_border = "#b5b4c9" 
cursor_fg = "#191c25" 
selection_bg = "#272935" 
selection_fg = "#b5b4c9"  
scrollbar_thumb = "#272935"
split = "#272935"
ansi = ["#191c25","#cf8164","#76a065","#ab924c","#8296b0","#a18daf","#659ea2","#b5b4c9"]
brights = ["#5b5f71","#fe9f7c","#92c47e","#d2b45f","#a0b9d8","#c6aed7","#7dc2c7","#f0ecfe"]
